aliases:
  - &restore-cache
    keys:
      - v2-test-{{ .Branch }}-{{ checksum "package.json" }}
      - v2-test-{{ .Branch }}

  - &save-node-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &save-ios-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules
      - ios/build

  - &install-node-dependencies |
    yarn

defaults: &defaults
  working_directory: ~/detoxSample

jobs:
  test-android:
    <<: *defaults
    docker:
      - image: circleci/android:api-29-node
    dependencies:
      pre:

    steps:
      - checkout
      - run: *install-node-dependencies
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Run Emulator
          background: true
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd testEmulator -noaudio -no-boot-anim -no-window -accel auto -verbose
      - run:
          name: Run Detox
          command: |
            yarn detox:android:debug

workflows:
  version: 2

  build:
    jobs:
      - test-android
