jobs:
  test-android:
    <<: *defaults
    docker:
      - image: circleci/android:api-28-node8

  steps:
    - checkout
    - run: npm install
    - run:
        name: Download Android Dependencies
        command: |
          ls
          cd android
          ./gradlew androidDependencies
          cd ../
    - run: sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
    - run: sdkmanager --licenses
    - run: echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-25;google_apis;armeabi-v7a"
    - run:
        name: Run emulator in background
        command: |
          sudo apt-get install libpulse0
          export ANDROID_SDK_ROOT=${ANDROID_HOME}
          export LD_LIBRARY_PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib emulator64-arm -avd testEmulator -noaudio -no-boot-anim -no-window -accel on -verbose -gpu swiftshader
          background: true
    - run: sudo npm install -g detox-cli
    - run:
        name: start pkg server
        command: npm start
        background: true
    - run: detox build -c android.sim.debug
    - run: detox test -c android.sim.debug -l trace
workflows:
  version: 2
  build:
    jobs:
      - test-android
