aliases:
  - &restore-cache
    keys:
      - v2-test-{{ .Branch }}-{{ checksum "package.json" }}
      - v2-test-{{ .Branch }}

  - &save-node-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &save-ios-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules
      - ios/build

  - &install-node-dependencies |
    yarn

defaults: &defaults
  working_directory: ~/detoxSample

jobs:
  test-android:
    <<: *defaults
    docker:
      - image: circleci/android:api-29
    dependencies:
      pre:

    steps:
      - checkout
      - run: *install-node-dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Detox
          command: |
            yarn detox:android:debug

workflows:
  version: 2

  build:
    jobs:
      - test-android
