aliases:
  - &restore-cache
    keys:
      - v2-test-{{ .Branch }}-{{ checksum "package.json" }}
      - v2-test-{{ .Branch }}

  - &save-node-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &install-node-dependencies |
    yarn

defaults: &defaults
  working_directory: ~/detoxSample

jobs:
  test-android:
    <<: *defaults
    docker:
      - image: circleci/android:api-29-node
    environment:
      SKIP_OKBUCK: true
      EXTRA_OKBUCK_ARGS: --stacktrace
      JVM_OPTS: -Xmx3200m
    dependencies:
      pre:

    steps:
      - checkout
      - run: *install-node-dependencies
      - run: sudo npm install -g detox-cli
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies
      - run:
          name: Setup emulator
          command: |
            sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Run Emulator
          background: true
          command: emulator -avd testEmulator -noaudio -no-boot-anim -no-window -accel auto -skin WVGA800 -verbose
      - run: detox build -c android.sim.debug
      - run: detox test -c android.sim.debug

workflows:
  version: 2

  build:
    jobs:
      - test-android
